# The URL the site will be built for
base_url = "https://katsutoshii.github.io"
compile_sass = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
