
[[links]]
title = "About"
url = "/"

[[links]]
title = "Projects"
url = "/projects/"

[[links]]
title = "Resume"
url = "/resume/"

[[links]]
title = "CV"
url = "/cv/"

[[links]]
title = "Devlog"
url = "/devlog/"
